.PHONY: all run clean

all:
	@echo "Python solution. Run:"
	@echo "  python3 blocksworld.py tests/probA03.bwp -H H2 --trace -MAX_ITERS 200000"

run:
	python3 blocksworld.py tests/probA03.bwp -H H2 --trace -MAX_ITERS 1000000

clean:
	@echo "Nothing to clean for Python build."
